version: '3'

services:
  reviews:
    build: .
    links:
      - redis
    depends_on:
      - redis
    ports:
      - '3003:3003'
    environment:
      - REDIS_PORT_6379_TCP_ADDR:"redis:6379"

  redis:
    image: redis:latest
    ports: 
      - '6379:6379'
